name: autofix.ci
on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci && npx eslint . --fix && npx prettier . -w
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
